services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cesizen_frontend_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - cesizen_network

networks:
  cesizen_network:
    driver: bridge
