# Configuration des environnements de déploiement
# Ce fichier définit les règles et secrets pour chaque environnement

# Environnement Staging
staging:
  # Règles de protection
  protection_rules:
    - required_reviews: 1
    - dismiss_stale_reviews: true
    - require_code_owner_reviews: false
    - required_status_checks:
        - "Test and Build"
        - "Docker Check"
        - "Security Check"
  
  # Variables d'environnement
  environment_variables:
    NODE_ENV: staging
    REACT_APP_API_URL: https://staging-api.cesizen.com/api
    REACT_APP_ENVIRONMENT: staging
  
  # Secrets requis
  required_secrets:
    - STAGING_DEPLOY_KEY
    - STAGING_DATABASE_URL
    - STAGING_API_KEY

# Environnement Production
production:
  # Règles de protection plus strictes
  protection_rules:
    - required_reviews: 2
    - dismiss_stale_reviews: true
    - require_code_owner_reviews: true
    - required_status_checks:
        - "Test and Build"
        - "Docker Check"
        - "Security Check"
        - "Deploy to Staging"
    - restrictions:
        teams: ["devops", "senior-developers"]
  
  # Variables d'environnement
  environment_variables:
    NODE_ENV: production
    REACT_APP_API_URL: https://api.cesizen.com/api
    REACT_APP_ENVIRONMENT: production
  
  # Secrets requis
  required_secrets:
    - PRODUCTION_DEPLOY_KEY
    - PRODUCTION_DATABASE_URL
    - PRODUCTION_API_KEY
    - PRODUCTION_SSL_CERT
