name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  # Vérification de base
  basic-check:
    name: Basic Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check code formatting
        run: npm run format:check --if-present
        
      - name: Run linting
        run: npm run lint --if-present
        
      - name: Run type checking
        run: npm run type-check --if-present
        
      - name: Run tests
        run: npm test --if-present -- --watchAll=false --coverage
        
      - name: Build application
        run: npm run build
        
      - name: Check bundle size
        run: npm run build:analyze --if-present

  # Vérification Docker
  docker-check:
    name: Docker Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: cesizen-frontend:pr-check
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Vérification de sécurité
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        
      - name: Check for known vulnerabilities
        run: npm audit --audit-level=high --json > audit-results.json || true
        
      - name: Upload security results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit
          path: audit-results.json
          retention-days: 30
